name: dotfiles test

on:
  pull_request:
    branches:
      - main
    path:
      - 'installer.sh'

jobs:
  test:
    name: test mel9y/dotfiles
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: installer
        run: ./installer.sh
