name: dotfiles test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test m2en/dotfiles
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: test - link symbolic
        run: make link

      - name: test - develop preparetion
        run: make develop
